name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            LaTeX/DA_Snowboards/_DABA.TEX
          extra_fonts: |
            LaTeX/DA_Snowboards/fonts/segoeui.ttf
        env:
          TEXINPUTS: ".:.//:"
